export interface TutorialReward {
  type: 'resources' | 'solar';
  fer?: number;
  silice?: number;
  xenogas?: number;
  solar?: number;
}

export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  hint: string;
  category: 'economy' | 'facilities' | 'research' | 'military' | 'exploration';
  checkType: 'building_level' | 'research_level' | 'ship_count' | 'defense_count' | 'has_fleet_sent' | 'has_colony' | 'has_sent_mission';
  checkTarget: string;
  checkValue: number;
  reward: TutorialReward;
  navigateTo?: string;
}

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'ferro_mine_1',
    title: 'Premiers pas : Ferro Mine',
    description: 'Construisez votre Ferro Mine au niveau 1 pour commencer la production de fer.',
    hint: 'Allez dans l\'onglet Bâtiments et construisez la Ferro Mine.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferMine',
    checkValue: 1,
    reward: { type: 'resources', fer: 500 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'power_plant_1',
    title: 'Énergie vitale',
    description: 'Construisez une Power Plant pour alimenter vos mines en énergie.',
    hint: 'Sans énergie, vos mines fonctionneront au ralenti !',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'solarPlant',
    checkValue: 1,
    reward: { type: 'resources', fer: 300, silice: 150 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'silica_mine_1',
    title: 'Silice cristalline',
    description: 'Construisez une Silica Mine pour diversifier votre production.',
    hint: 'La silice est essentielle pour les technologies avancées.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'siliceMine',
    checkValue: 1,
    reward: { type: 'resources', silice: 500 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'ferro_mine_2',
    title: 'Expansion minière',
    description: 'Améliorez votre Ferro Mine au niveau 2 pour augmenter la production.',
    hint: 'Plus le niveau est élevé, plus la production est importante.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferMine',
    checkValue: 2,
    reward: { type: 'resources', fer: 800, silice: 400 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'xeno_well_1',
    title: 'Gaz alien',
    description: 'Construisez un Xeno Well pour produire du Xenogas.',
    hint: 'Le Xenogas est rare mais indispensable pour la recherche.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'xenogasRefinery',
    checkValue: 1,
    reward: { type: 'resources', xenogas: 500 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'power_plant_3',
    title: 'Surplus énergétique',
    description: 'Améliorez la Power Plant au niveau 3 pour soutenir votre croissance.',
    hint: 'Gardez toujours un surplus d\'énergie positif.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'solarPlant',
    checkValue: 3,
    reward: { type: 'resources', fer: 1000, silice: 500, xenogas: 200 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'automata_foundry_1',
    title: 'Automatisation',
    description: 'Construisez l\'Automata Foundry pour accélérer toutes vos constructions.',
    hint: 'L\'Automata Foundry réduit le temps de construction de tous les bâtiments.',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'roboticsFactory',
    checkValue: 1,
    reward: { type: 'resources', fer: 2000, silice: 1000, xenogas: 500 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'research_lab_1',
    title: 'Savoir scientifique',
    description: 'Construisez l\'Arcology Research Lab pour débloquer la recherche.',
    hint: 'La recherche ouvre la voie aux technologies militaires et d\'exploration.',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'researchLab',
    checkValue: 1,
    reward: { type: 'resources', fer: 1500, silice: 2000, xenogas: 1000 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'quantum_flux_1',
    title: 'Première recherche',
    description: 'Recherchez le Flux Quantique niveau 1.',
    hint: 'Allez dans l\'onglet Recherche et lancez le Flux Quantique.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'quantumFlux',
    checkValue: 1,
    reward: { type: 'resources', silice: 2000, xenogas: 1000 },
    navigateTo: '/(tabs)/research',
  },
  {
    id: 'particle_beam_1',
    title: 'Armes offensives',
    description: 'Recherchez le Rayon à Particules niveau 1.',
    hint: 'Base de toute la technologie offensive.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'particleBeam',
    checkValue: 1,
    reward: { type: 'resources', fer: 1500, silice: 1000 },
    navigateTo: '/(tabs)/research',
  },
  {
    id: 'chemical_drive_1',
    title: 'Propulsion spatiale',
    description: 'Recherchez la Propulsion Chimique pour débloquer vos premiers vaisseaux.',
    hint: 'Sans propulsion, pas de vaisseaux !',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'chemicalDrive',
    checkValue: 1,
    reward: { type: 'resources', fer: 2000, silice: 2000 },
    navigateTo: '/(tabs)/research',
  },
  {
    id: 'automata_foundry_2',
    title: 'Fonderie avancée',
    description: 'Améliorez l\'Automata Foundry au niveau 2 pour débloquer le chantier spatial.',
    hint: 'Prérequis pour l\'Orbital Assembly Dock.',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'roboticsFactory',
    checkValue: 2,
    reward: { type: 'resources', fer: 3000, silice: 1500, xenogas: 1000 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'shipyard_1',
    title: 'Chantier spatial',
    description: 'Construisez l\'Orbital Assembly Dock pour produire des vaisseaux.',
    hint: 'Le dock orbital est le coeur de votre flotte !',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'shipyard',
    checkValue: 1,
    reward: { type: 'resources', fer: 5000, silice: 3000, xenogas: 1000 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'first_defense',
    title: 'Défenses planétaires',
    description: 'Construisez au moins 3 Tourelles Cinétiques pour protéger votre planète.',
    hint: 'Allez dans le Chantier Naval et construisez des défenses.',
    category: 'military',
    checkType: 'defense_count',
    checkTarget: 'kineticTurret',
    checkValue: 3,
    reward: { type: 'resources', fer: 5000, silice: 2000 },
    navigateTo: '/(tabs)/shipyard?tab=defenses&scrollTo=kineticTurret',
  },
  {
    id: 'first_ship',
    title: 'Premier vaisseau',
    description: 'Construisez votre premier Nova Scout.',
    hint: 'Le Nova Scout est un intercepteur rapide et agile.',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'novaScout',
    checkValue: 1,
    reward: { type: 'resources', fer: 5000, silice: 3000, xenogas: 1000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=novaScout',
  },
  {
    id: 'espionage_tech_1',
    title: 'Renseignement',
    description: 'Recherchez le Sonar Cosmique pour espionner vos ennemis.',
    hint: 'L\'espionnage est crucial avant toute attaque.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'espionageTech',
    checkValue: 1,
    reward: { type: 'resources', fer: 3000, silice: 5000, xenogas: 2000 },
    navigateTo: '/(tabs)/research',
  },
  {
    id: 'spy_probes',
    title: 'Sondes furtives',
    description: 'Construisez 5 Spectre Sondes pour espionner d\'autres joueurs.',
    hint: 'Les sondes sont indispensables pour collecter des renseignements.',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'spectreSonde',
    checkValue: 5,
    reward: { type: 'resources', fer: 3000, silice: 5000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=spectreSonde',
  },
  {
    id: 'cargo_ships',
    title: 'Transport de ressources',
    description: 'Construisez 2 Atlas Cargo pour transporter des ressources.',
    hint: 'Les cargos sont essentiels pour le commerce et le pillage.',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'atlasCargo',
    checkValue: 2,
    reward: { type: 'resources', fer: 5000, silice: 5000, xenogas: 2000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=atlasCargo',
  },
  {
    id: 'send_espionage',
    title: 'Première mission d\'espionnage',
    description: 'Envoyez vos Spectre Sondes espionner une planète ennemie.',
    hint: 'Allez dans la Galaxie, sélectionnez un joueur et lancez une mission d\'espionnage.',
    category: 'exploration',
    checkType: 'has_sent_mission',
    checkTarget: 'espionage',
    checkValue: 1,
    reward: { type: 'resources', fer: 5000, silice: 5000, xenogas: 2000 },
    navigateTo: '/(tabs)/galaxy',
  },
  {
    id: 'send_attack',
    title: 'Premier assaut',
    description: 'Lancez votre première attaque contre une planète ennemie.',
    hint: 'Sélectionnez une cible dans la Galaxie et envoyez une flotte en mission d\'attaque.',
    category: 'military',
    checkType: 'has_sent_mission',
    checkTarget: 'attack',
    checkValue: 1,
    reward: { type: 'resources', fer: 10000, silice: 8000, xenogas: 5000 },
    navigateTo: '/(tabs)/galaxy',
  },
  {
    id: 'build_colony_ship',
    title: 'Barge Coloniale',
    description: 'Construisez une Barge Coloniale pour coloniser de nouveaux mondes.',
    hint: 'Vous aurez besoin de la Xéno-Cartographie et d\'un Réacteur à Impulsions niv. 3.',
    category: 'exploration',
    checkType: 'ship_count',
    checkTarget: 'colonyShip',
    checkValue: 1,
    reward: { type: 'resources', fer: 15000, silice: 15000, xenogas: 10000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=colonyShip',
  },
  {
    id: 'first_colony',
    title: 'Expansion interstellaire',
    description: 'Établissez votre première colonie sur une planète vierge.',
    hint: 'Envoyez votre Barge Coloniale vers une position vide dans la Galaxie avec la mission Coloniser.',
    category: 'exploration',
    checkType: 'has_colony',
    checkTarget: '',
    checkValue: 1,
    reward: { type: 'solar', solar: 150 },
    navigateTo: '/(tabs)/galaxy',
  },
  {
    id: 'ferro_store_1',
    title: 'Stockage sécurisé',
    description: 'Construisez un Ferro Store pour augmenter votre capacité de stockage.',
    hint: 'Sans stockage, les ressources excédentaires sont perdues.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferroStore',
    checkValue: 1,
    reward: { type: 'resources', fer: 5000, silice: 3000 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'computer_tech_1',
    title: 'Intelligence artificielle',
    description: 'Recherchez l\'IA Stratégique pour augmenter votre capacité de flottes.',
    hint: 'Plus votre IA est avancée, plus vous pouvez envoyer de flottes simultanément.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'computerTech',
    checkValue: 1,
    reward: { type: 'solar', solar: 50 },
    navigateTo: '/(tabs)/research',
  },
  {
    id: 'ferro_mine_5',
    title: 'Empire minier',
    description: 'Améliorez la Ferro Mine au niveau 5.',
    hint: 'Une économie solide est la base de tout empire.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferMine',
    checkValue: 5,
    reward: { type: 'solar', solar: 75 },
    navigateTo: '/(tabs)/buildings',
  },
  {
    id: 'fleet_5_scouts',
    title: 'Escadron de chasse',
    description: 'Assemblez une flotte de 5 Nova Scouts.',
    hint: 'La force est dans le nombre !',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'novaScout',
    checkValue: 5,
    reward: { type: 'solar', solar: 100 },
    navigateTo: '/(tabs)/shipyard?scrollTo=novaScout',
  },
];

export const TUTORIAL_CATEGORIES = {
  economy: { label: 'Économie', color: '#D4A847' },
  facilities: { label: 'Infrastructures', color: '#8B5CF6' },
  research: { label: 'Recherche', color: '#22D3EE' },
  military: { label: 'Militaire', color: '#EF4444' },
  exploration: { label: 'Exploration', color: '#10B981' },
} as const;
