export const BUILDING_LORE: Record<string, string> = {
  ferMine: "Enfouie dans les veines tectoniques de la planète, la Ferro Mine extrait inlassablement le minerai brut qui alimentera votre empire. Chaque niveau supplémentaire creuse plus profondément dans le manteau planétaire.",
  siliceMine: "Les cristaux de silice, formés sous des pressions colossales depuis des millénaires, sont la clé des technologies avancées. Cette mine exploite les gisements cristallins avec une précision chirurgicale.",
  xenogasRefinery: "Le Xenogas, ce gaz alien aux propriétés uniques, est capturé et raffiné dans cette installation hermétique. Substance rare et volatile, il est indispensable à toute recherche de pointe.",
  solarPlant: "Des panneaux photovoltaïques de nouvelle génération convertissent le rayonnement stellaire en énergie pure. Sans elle, vos installations fonctionnent au ralenti.",
  ferroStore: "Un complexe d'entrepôts blindés et pressurisés, capable de stocker des quantités massives de fer raffiné à l'abri des raids ennemis.",
  silicaStore: "Des chambres de stockage pressurisées maintiennent les cristaux de silice dans des conditions optimales. La moindre contamination peut ruiner un lot entier.",
  xenoStore: "Des réservoirs cryogéniques maintiennent le Xenogas à des températures proches du zéro absolu, empêchant toute réaction spontanée de cette substance instable.",
  roboticsFactory: "L'Automata Foundry déploie des essaims de drones constructeurs autonomes qui accélèrent chaque projet de bâtiment. Plus la fonderie est avancée, plus rapide est l'édification.",
  shipyard: "Le Dock d'Assemblage Orbital est le cœur battant de votre flotte. Dans ses immenses cales, des vaisseaux de toutes tailles prennent forme sous les étincelles des soudures plasmatiques. Chaque niveau améliore la cadence de production des vaisseaux et défenses.",
  researchLab: "L'Arcology Research Lab est une cathédrale de la connaissance. Des scientifiques de toute la galaxie y repoussent les frontières du savoir, débloquant de nouvelles technologies. Chaque niveau accélère la vitesse de recherche de toutes les technologies.",
  naniteFactory: "Le Quantum Reactor Core utilise des assembleurs nanométriques pour reconfigurer la matière à l'échelle atomique. Chaque niveau divise par 2 le temps de toutes les constructions.",
  geoformEngine: "Le Geoform Engine remodèle la croûte planétaire elle-même, créant de nouveaux champs constructibles là où il n'y avait que roche stérile.",
};

export const RESEARCH_LORE: Record<string, string> = {
  quantumFlux: "La maîtrise du flux quantique permet de canaliser l'énergie du vide lui-même. Chaque avancée optimise le rendement de vos centrales.",
  particleBeam: "Concentrer des particules subatomiques en un faisceau destructeur : c'est l'essence même de cette technologie offensive fondamentale.",
  ionicStream: "Les flux ioniques perturbent les systèmes électroniques ennemis tout en renforçant vos propres boucliers énergétiques.",
  plasmaOverdrive: "La surchauffe plasmatique permet d'extraire davantage de ressources de chaque filon, et débloque les armes les plus destructrices. Chaque niveau augmente la production de Ferro (+1%), Silice (+0.66%) et Xenogas (+0.33%).",
  weaponsTech: "Des systèmes balistiques de plus en plus perfectionnés augmentent la puissance de feu de toutes vos unités de combat (+10% par niveau).",
  shieldTech: "Les champs déflecteurs créent une barrière d'énergie pure capable d'absorber les impacts. Chaque niveau renforce tous vos boucliers de 10%.",
  armorTech: "Les alliages nano-tressés renforcent la coque de chaque vaisseau et défense, augmentant leur résistance de 10% par niveau.",
  chemicalDrive: "La propulsion chimique classique : fiable et économique. Chaque niveau augmente de 10% la vitesse de base des vaisseaux équipés : Atlas Cargo, Atlas Cargo XL, Nova Scout, Manta Recup et Spectre Sonde.",
  impulseReactor: "Le réacteur à impulsions propulse vos vaisseaux grâce à des décharges d'énergie contrôlées. Chaque niveau augmente de 20% la vitesse de base des Pyro, Cyclone, Fer de Lance et Barge Coloniale. Au niveau 5, l'Atlas Cargo est rééquipé d'un réacteur à impulsions. Au niveau 17, la Manta Recup est également rééquipée.",
  voidDrive: "La voile hyperspatiale plie l'espace-temps. Chaque niveau augmente de 30% la vitesse de base des Nemesis, Bastion, Fulgurant et Titan Astral. Au niveau 8, le Pyro est rééquipé d'une voile hyperspatiale. Au niveau 15, la Manta Recup est également rééquipée.",
  computerTech: "L'IA Stratégique coordonne vos flottes avec une précision surhumaine. Chaque niveau permet d'envoyer une flotte supplémentaire simultanément.",
  espionageTech: "Le sonar cosmique capte les moindres émissions électromagnétiques ennemies, révélant leurs forces, leurs faiblesses et leurs ressources.",
  astrophysics: "La xéno-cartographie cartographie les mondes habitables de la galaxie, rendant possible la colonisation de nouvelles planètes. Chaque 2 niveaux de recherche débloquent un emplacement de colonie supplémentaire.",
  subspacialNodes: "Les nœuds subspatiaux compriment l'espace de stockage des cales, augmentant la capacité de fret de tous vos vaisseaux (+5%/niveau).",
  neuralMesh: "Le maillage neuronal connecte les laboratoires de vos différentes planètes en un seul réseau de recherche synchronisé. Chaque niveau permet d'ajouter le laboratoire d'une planète supplémentaire (le plus haut niveau en priorité) au calcul de vitesse de recherche.",
  gravitonTech: "La manipulation gravitationnelle est le sommet de la physique théorique. Elle débloque le Titan Astral, capable d'anéantir une lune.",
};

export const SHIP_LORE: Record<string, string> = {
  novaScout: "Rapide comme l'éclair et mortel en groupe, le Nova Scout est l'intercepteur favori des commandants agressifs. Sa maniabilité en fait un cauchemar pour les cibles isolées.",
  ferDeLance: "Le Fer de Lance porte bien son nom : c'est la pointe de votre offensive. Son blindage renforcé et son armement lourd en font un chasseur d'assaut redoutable.",
  cyclone: "Polyvalent et résistant, le Cyclone est le pilier de toute flotte organisée. Il excelle dans les engagements prolongés grâce à son équilibre parfait entre attaque et défense.",
  bastion: "Le Bastion est un vaisseau capital dont la seule présence fait trembler l'ennemi. Sa puissance de feu dévastatrice peut retourner le cours d'une bataille.",
  pyro: "Spécialisé dans la destruction des défenses planétaires, le Pyro bombarde les installations au sol avec une précision chirurgicale. Lent mais dévastateur.",
  nemesis: "Le Nemesis est un croiseur anti-chasseurs ultra-rapide. Sa vitesse supérieure et son armement ciblé font de lui le fléau des escadrons légers.",
  fulgurant: "Le Fulgurant est un destroyer massif dont les canons principaux peuvent percer n'importe quel blindage. Rien ne résiste à sa puissance brute.",
  titanAstral: "Le Titan Astral est l'arme ultime, une station de combat mobile capable d'annihiler des flottes entières et même de détruire des lunes. Sa construction est un exploit technologique.",
  atlasCargo: "Le fidèle Atlas Cargo transporte vos ressources d'un système à l'autre. Peu armé mais essentiel à toute économie interstellaire florissante.",
  atlasCargoXL: "Version agrandie de l'Atlas, le Cargo XL offre une capacité de fret massive pour les opérations logistiques d'envergure.",
  colonyShip: "La Barge Coloniale embarque tout le nécessaire pour établir une nouvelle colonie : habitats, générateurs, et les premiers colons prêts à conquérir un nouveau monde.",
  mantaRecup: "La Manta Recup est équipée de bras magnétiques géants qui récupèrent les débris métalliques flottant dans le vide après une bataille spatiale.",
  spectreSonde: "Furtive et presque indétectable, la Spectre Sonde infiltre les systèmes ennemis pour collecter des renseignements précieux sur leurs forces et ressources.",
  heliosRemorqueur: "Ce satellite solaire orbital capture l'énergie stellaire et la transmet directement à vos installations au sol. +30 énergie par unité.",
};

export const DEFENSE_LORE: Record<string, string> = {
  kineticTurret: "Simple mais terriblement efficace, la tourelle cinétique projette des salves de projectiles métalliques à vitesse hypersonique. Le cauchemar des chasseurs légers.",
  pulseCannon: "Le canon à impulsion concentre l'énergie en rafales dévastatrices. Sa cadence de tir élevée et sa précision en font un excellent anti-aérien.",
  beamCannon: "Un faisceau d'énergie continu qui découpe littéralement les blindages moyens. Sa portée et sa puissance en font une défense de choix.",
  massDriver: "Le canon de masse projette des obus hyper-denses à une fraction de la vitesse de la lumière. Un seul impact peut mettre hors service un vaisseau lourd.",
  ionProjector: "Le projecteur ionique génère une onde de choc électromagnétique qui désactive l'électronique ennemie et fragilise les boucliers.",
  solarCannon: "Alimenté par un mini-réacteur stellaire, le canon solaire lance des torrents de plasma surchauffé. L'arme défensive la plus puissante jamais conçue.",
  smallShield: "Un dôme d'énergie protecteur couvrant une zone restreinte de la planète. Premier rempart contre les bombardements orbitaux.",
  largeShield: "Le grand bouclier planétaire englobe toute la surface habitable dans une bulle d'énergie quasi-impénétrable.",
};
