export interface TutorialReward {
  type: 'resources' | 'solar';
  fer?: number;
  silice?: number;
  xenogas?: number;
  solar?: number;
}

export interface TutorialStep {
  id: string;
  chapterId: string;
  order: number;
  title: string;
  description: string;
  explanation: string;
  hint: string;
  category: 'economy' | 'facilities' | 'research' | 'military' | 'exploration';
  checkType: 'building_level' | 'research_level' | 'ship_count' | 'defense_count' | 'server_event' | 'transaction_check';
  checkTarget: string;
  checkValue: number;
  validationSource: string;
  reward: TutorialReward;
  navigateTo?: string;
}

export interface TutorialChapter {
  id: string;
  title: string;
  description: string;
  stepIds: string[];
}

export const TUTORIAL_CHAPTERS: TutorialChapter[] = [
  {
    id: 'ch1',
    title: 'Les Fondations',
    description: 'Votre planète est un monde vierge. Avant de conquérir les étoiles, bâtissez une économie solide.',
    stepIds: ['ch1_ferro_mine_1', 'ch1_power_plant_1', 'ch1_silica_mine_1', 'ch1_ferro_mine_2', 'ch1_power_plant_2', 'ch1_xeno_well_1', 'ch1_ferro_store_1'],
  },
  {
    id: 'ch2',
    title: 'Infrastructures & Recherche',
    description: 'Vos mines tournent, votre énergie est stable. Posez les fondations technologiques de votre empire.',
    stepIds: ['ch2_automata_1', 'ch2_research_lab_1', 'ch2_quantum_flux_1', 'ch2_particle_beam_1', 'ch2_chemical_drive_1'],
  },
  {
    id: 'ch3',
    title: 'Puissance Militaire',
    description: 'Votre technologie est prête. Forgez votre flotte et vos défenses.',
    stepIds: ['ch3_automata_2', 'ch3_shipyard_1', 'ch3_first_defense', 'ch3_first_ship', 'ch3_spy_probes', 'ch3_cargo_ships'],
  },
  {
    id: 'ch4',
    title: 'Opérations Spatiales',
    description: 'Votre flotte est prête. Chaque mission a un objectif précis.',
    stepIds: ['ch4_espionage_tech_1', 'ch4_send_espionage', 'ch4_send_attack', 'ch4_quantum_shield', 'ch4_computer_tech_1'],
  },
  {
    id: 'ch5',
    title: 'Expansion',
    description: 'Vous maîtrisez le combat. Étendez votre empire au-delà de votre monde natal.',
    stepIds: ['ch5_colony_ship', 'ch5_first_colony', 'ch5_fleet_5_scouts', 'ch5_ferro_mine_5'],
  },
];

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'ch1_ferro_mine_1',
    chapterId: 'ch1',
    order: 0,
    title: 'Extraction primaire',
    description: 'Construisez votre Ferro Mine niveau 1 pour commencer la production de fer.',
    explanation: 'Le fer est la ressource de base de votre empire. Toutes les constructions en nécessitent. La Ferro Mine produit du fer en continu.',
    hint: 'Allez dans l\'onglet Bâtiments et construisez la Ferro Mine.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferMine',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 500 },
    navigateTo: '/(tabs)/buildings?scrollTo=ferMine',
  },
  {
    id: 'ch1_power_plant_1',
    chapterId: 'ch1',
    order: 1,
    title: 'Courant vital',
    description: 'Construisez une Power Plant niveau 1 pour alimenter vos mines.',
    explanation: 'Chaque mine consomme de l\'énergie. Sans énergie suffisante, vos mines tournent au ralenti et votre production chute. La Power Plant est votre source d\'énergie principale.',
    hint: 'Sans énergie, vos mines fonctionneront au ralenti !',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'solarPlant',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 300, silice: 150 },
    navigateTo: '/(tabs)/buildings?scrollTo=solarPlant',
  },
  {
    id: 'ch1_silica_mine_1',
    chapterId: 'ch1',
    order: 2,
    title: 'Cristaux précieux',
    description: 'Construisez une Silica Mine niveau 1 pour diversifier votre production.',
    explanation: 'La silice est la deuxième ressource majeure. Elle est indispensable pour la recherche et les vaisseaux avancés. Diversifier vos ressources est essentiel.',
    hint: 'La silice est essentielle pour les technologies avancées.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'siliceMine',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', silice: 500 },
    navigateTo: '/(tabs)/buildings?scrollTo=siliceMine',
  },
  {
    id: 'ch1_ferro_mine_2',
    chapterId: 'ch1',
    order: 3,
    title: 'Montée en puissance',
    description: 'Améliorez la Ferro Mine niveau 2 pour augmenter la production.',
    explanation: 'Chaque niveau augmente la production mais aussi la consommation d\'énergie. Surveillez toujours votre bilan énergétique.',
    hint: 'Plus le niveau est élevé, plus la production est importante.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferMine',
    checkValue: 2,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 800, silice: 400 },
    navigateTo: '/(tabs)/buildings?scrollTo=ferMine',
  },
  {
    id: 'ch1_power_plant_2',
    chapterId: 'ch1',
    order: 4,
    title: 'Équilibre énergétique',
    description: 'Améliorez la Power Plant niveau 2 pour soutenir votre croissance.',
    explanation: 'Votre consommation a augmenté avec la mine. Maintenir un surplus d\'énergie est crucial : un déficit réduit TOUTE votre production.',
    hint: 'Gardez toujours un surplus d\'énergie positif.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'solarPlant',
    checkValue: 2,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 500, silice: 300 },
    navigateTo: '/(tabs)/buildings?scrollTo=solarPlant',
  },
  {
    id: 'ch1_xeno_well_1',
    chapterId: 'ch1',
    order: 5,
    title: 'Gaz extraterrestre',
    description: 'Construisez un Xeno Well niveau 1 pour produire du Xenogas.',
    explanation: 'Le Xenogas est la troisième et la plus rare des ressources. Il est indispensable pour la recherche avancée et les vaisseaux lourds.',
    hint: 'Le Xenogas est rare mais indispensable pour la recherche.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'xenogasRefinery',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', xenogas: 500 },
    navigateTo: '/(tabs)/buildings?scrollTo=xenogasRefinery',
  },
  {
    id: 'ch1_ferro_store_1',
    chapterId: 'ch1',
    order: 6,
    title: 'Stockage sécurisé',
    description: 'Construisez un Ferro Store niveau 1 pour augmenter votre capacité de stockage.',
    explanation: 'Vos entrepôts ont une capacité limitée. Au-delà, la production est perdue. Le stockage protège aussi une partie de vos ressources en cas d\'attaque.',
    hint: 'Sans stockage, les ressources excédentaires sont perdues.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferroStore',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 1000, silice: 500 },
    navigateTo: '/(tabs)/buildings?scrollTo=ferroStore',
  },
  {
    id: 'ch2_automata_1',
    chapterId: 'ch2',
    order: 7,
    title: 'Automatisation',
    description: 'Construisez l\'Automata Foundry niveau 1 pour accélérer vos constructions.',
    explanation: 'L\'Automata Foundry accélère TOUTES vos constructions. Plus son niveau est élevé, plus vos bâtiments se construisent vite. C\'est un investissement qui se rentabilise rapidement.',
    hint: 'L\'Automata Foundry réduit le temps de construction de tous les bâtiments.',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'roboticsFactory',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 2000, silice: 1000, xenogas: 500 },
    navigateTo: '/(tabs)/buildings?scrollTo=roboticsFactory',
  },
  {
    id: 'ch2_research_lab_1',
    chapterId: 'ch2',
    order: 8,
    title: 'Laboratoire de recherche',
    description: 'Construisez l\'Arcology Research Lab niveau 1 pour débloquer la recherche.',
    explanation: 'Le laboratoire débloque l\'onglet Recherche. La recherche est permanente : elle s\'applique à TOUTES vos planètes. C\'est votre avantage stratégique à long terme.',
    hint: 'La recherche ouvre la voie aux technologies militaires et d\'exploration.',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'researchLab',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 1500, silice: 2000, xenogas: 1000 },
    navigateTo: '/(tabs)/buildings?scrollTo=researchLab',
  },
  {
    id: 'ch2_quantum_flux_1',
    chapterId: 'ch2',
    order: 9,
    title: 'Flux Quantique',
    description: 'Recherchez le Flux Quantique niveau 1.',
    explanation: 'Le Flux Quantique est le prérequis de nombreuses technologies. Il améliore aussi le rendement de vos mines. C\'est la première pierre de votre arbre technologique.',
    hint: 'Allez dans l\'onglet Recherche et lancez le Flux Quantique.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'quantumFlux',
    checkValue: 1,
    validationSource: 'research_complete',
    reward: { type: 'resources', silice: 2000, xenogas: 1000 },
    navigateTo: '/(tabs)/research?scrollTo=quantumFlux',
  },
  {
    id: 'ch2_particle_beam_1',
    chapterId: 'ch2',
    order: 10,
    title: 'Armement de base',
    description: 'Recherchez le Rayon à Particules niveau 1.',
    explanation: 'Cette technologie est le fondement de tout armement offensif. Elle débloque les tourelles défensives et améliore la puissance de vos futurs vaisseaux.',
    hint: 'Base de toute la technologie offensive.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'particleBeam',
    checkValue: 1,
    validationSource: 'research_complete',
    reward: { type: 'resources', fer: 1500, silice: 1000 },
    navigateTo: '/(tabs)/research?scrollTo=particleBeam',
  },
  {
    id: 'ch2_chemical_drive_1',
    chapterId: 'ch2',
    order: 11,
    title: 'Propulsion spatiale',
    description: 'Recherchez la Propulsion Chimique pour débloquer vos premiers vaisseaux.',
    explanation: 'Sans propulsion, pas de vaisseaux. La Propulsion Chimique est le moteur de base : vos premiers vaisseaux l\'utilisent. Des propulsions plus rapides viendront ensuite.',
    hint: 'Sans propulsion, pas de vaisseaux !',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'chemicalDrive',
    checkValue: 1,
    validationSource: 'research_complete',
    reward: { type: 'resources', fer: 2000, silice: 2000 },
    navigateTo: '/(tabs)/research?scrollTo=chemicalDrive',
  },
  {
    id: 'ch3_automata_2',
    chapterId: 'ch3',
    order: 12,
    title: 'Fonderie avancée',
    description: 'Améliorez l\'Automata Foundry au niveau 2 pour débloquer le chantier spatial.',
    explanation: 'Prérequis pour l\'Orbital Assembly Dock. L\'automatisation avancée permet de construire des structures spatiales complexes.',
    hint: 'Prérequis pour l\'Orbital Assembly Dock.',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'roboticsFactory',
    checkValue: 2,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 3000, silice: 1500, xenogas: 1000 },
    navigateTo: '/(tabs)/buildings?scrollTo=roboticsFactory',
  },
  {
    id: 'ch3_shipyard_1',
    chapterId: 'ch3',
    order: 13,
    title: 'Chantier spatial',
    description: 'Construisez l\'Orbital Assembly Dock pour produire des vaisseaux et défenses.',
    explanation: 'Le chantier spatial vous permet de construire des vaisseaux ET des défenses. C\'est le coeur de votre puissance militaire. Sans lui, vous êtes une cible sans défense.',
    hint: 'Le dock orbital est le coeur de votre flotte !',
    category: 'facilities',
    checkType: 'building_level',
    checkTarget: 'shipyard',
    checkValue: 1,
    validationSource: 'building_complete',
    reward: { type: 'resources', fer: 5000, silice: 3000, xenogas: 1000 },
    navigateTo: '/(tabs)/buildings?scrollTo=shipyard',
  },
  {
    id: 'ch3_first_defense',
    chapterId: 'ch3',
    order: 14,
    title: 'Bouclier planétaire',
    description: 'Construisez 3 Tourelles Cinétiques pour protéger votre planète.',
    explanation: 'Les défenses protègent votre planète quand vous êtes hors-ligne. Elles ne coûtent pas de carburant et se reconstruisent partiellement après un combat.',
    hint: 'Allez dans le Chantier Naval et construisez des défenses.',
    category: 'military',
    checkType: 'defense_count',
    checkTarget: 'kineticTurret',
    checkValue: 3,
    validationSource: 'shipyard_complete',
    reward: { type: 'resources', fer: 5000, silice: 2000 },
    navigateTo: '/(tabs)/shipyard?tab=defenses&scrollTo=kineticTurret',
  },
  {
    id: 'ch3_first_ship',
    chapterId: 'ch3',
    order: 15,
    title: 'Premier chasseur',
    description: 'Construisez votre premier Nova Scout.',
    explanation: 'Le Nova Scout est un intercepteur rapide et polyvalent. Il sera votre premier outil d\'exploration et de combat. Chaque vaisseau a des stats d\'attaque, bouclier et structure.',
    hint: 'Le Nova Scout est un intercepteur rapide et agile.',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'novaScout',
    checkValue: 1,
    validationSource: 'shipyard_complete',
    reward: { type: 'resources', fer: 5000, silice: 3000, xenogas: 1000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=novaScout',
  },
  {
    id: 'ch3_spy_probes',
    chapterId: 'ch3',
    order: 16,
    title: 'Yeux dans l\'espace',
    description: 'Construisez 5 Spectre Sondes pour espionner d\'autres joueurs.',
    explanation: 'Les sondes d\'espionnage sont légères et rapides. Elles permettent de scanner les planètes ennemies AVANT d\'attaquer. Ne jamais attaquer à l\'aveugle !',
    hint: 'Les sondes sont indispensables pour collecter des renseignements.',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'spectreSonde',
    checkValue: 5,
    validationSource: 'shipyard_complete',
    reward: { type: 'resources', fer: 3000, silice: 5000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=spectreSonde',
  },
  {
    id: 'ch3_cargo_ships',
    chapterId: 'ch3',
    order: 17,
    title: 'Logistique spatiale',
    description: 'Construisez 2 Atlas Cargo pour transporter des ressources.',
    explanation: 'Les cargos transportent les ressources pillées après une attaque. Sans cargo, vous ne pouvez pas ramener de butin. Ils servent aussi au transport entre vos planètes.',
    hint: 'Les cargos sont essentiels pour le commerce et le pillage.',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'atlasCargo',
    checkValue: 2,
    validationSource: 'shipyard_complete',
    reward: { type: 'resources', fer: 5000, silice: 5000, xenogas: 2000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=atlasCargo',
  },
  {
    id: 'ch4_espionage_tech_1',
    chapterId: 'ch4',
    order: 18,
    title: 'Sonar cosmique',
    description: 'Recherchez le Sonar Cosmique niveau 1 pour espionner vos ennemis.',
    explanation: 'Le niveau d\'espionnage détermine la quantité d\'informations obtenues sur l\'ennemi. Un niveau supérieur à celui du défenseur révèle plus de détails.',
    hint: 'L\'espionnage est crucial avant toute attaque.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'espionageTech',
    checkValue: 1,
    validationSource: 'research_complete',
    reward: { type: 'resources', fer: 3000, silice: 5000, xenogas: 2000 },
    navigateTo: '/(tabs)/research?scrollTo=espionageTech',
  },
  {
    id: 'ch4_send_espionage',
    chapterId: 'ch4',
    order: 19,
    title: 'Renseignement tactique',
    description: 'Espionnez une planète ennemie et obtenez un rapport d\'espionnage.',
    explanation: 'Trouvez un joueur dans la Galaxie et envoyez vos sondes. Le rapport vous dira si la cible vaut la peine d\'être attaquée. La mission doit arriver à destination.',
    hint: 'Allez dans la Galaxie, sélectionnez un joueur et lancez une mission d\'espionnage.',
    category: 'exploration',
    checkType: 'server_event',
    checkTarget: 'espionage_report_created',
    checkValue: 1,
    validationSource: 'espionage_report_created',
    reward: { type: 'resources', fer: 5000, silice: 5000, xenogas: 2000 },
    navigateTo: '/(tabs)/galaxy',
  },
  {
    id: 'ch4_send_attack',
    chapterId: 'ch4',
    order: 20,
    title: 'Premier assaut',
    description: 'Attaquez une planète ennemie et recevez un rapport de combat.',
    explanation: 'Choisissez une cible faible d\'après votre rapport d\'espionnage. Le combat se résout automatiquement à l\'arrivée. La flotte doit arriver et combattre.',
    hint: 'Sélectionnez une cible dans la Galaxie et envoyez une flotte en mission d\'attaque.',
    category: 'military',
    checkType: 'server_event',
    checkTarget: 'combat_report_created',
    checkValue: 1,
    validationSource: 'combat_report_created',
    reward: { type: 'resources', fer: 10000, silice: 8000, xenogas: 5000 },
    navigateTo: '/(tabs)/galaxy',
  },
  {
    id: 'ch4_quantum_shield',
    chapterId: 'ch4',
    order: 21,
    title: 'Défense Quantique',
    description: 'Achetez un Bouclier Quantique pour renforcer vos défenses planétaires.',
    explanation: 'Le Bouclier Quantique est une défense avancée qui protège votre planète contre les attaques ennemies. Il absorbe une partie des dégâts avant que vos tourelles ne soient touchées.',
    hint: 'Rendez-vous dans la boutique et achetez un Bouclier Quantique.',
    category: 'military',
    checkType: 'transaction_check',
    checkTarget: 'buy_shield',
    checkValue: 1,
    validationSource: 'solar_transaction',
    reward: { type: 'resources', fer: 8000, silice: 6000, xenogas: 3000 },
    navigateTo: '/(tabs)/shipyard?tab=defenses',
  },
  {
    id: 'ch4_computer_tech_1',
    chapterId: 'ch4',
    order: 22,
    title: 'IA stratégique',
    description: 'Recherchez l\'IA Stratégique niveau 1 pour envoyer plus de flottes.',
    explanation: 'L\'IA Stratégique augmente le nombre de flottes que vous pouvez envoyer simultanément. Par défaut, vous ne pouvez envoyer qu\'une seule flotte.',
    hint: 'Plus votre IA est avancée, plus vous pouvez envoyer de flottes simultanément.',
    category: 'research',
    checkType: 'research_level',
    checkTarget: 'computerTech',
    checkValue: 1,
    validationSource: 'research_complete',
    reward: { type: 'solar', solar: 50 },
    navigateTo: '/(tabs)/research?scrollTo=computerTech',
  },
  {
    id: 'ch5_colony_ship',
    chapterId: 'ch5',
    order: 23,
    title: 'Barge coloniale',
    description: 'Construisez une Barge Coloniale pour coloniser de nouveaux mondes.',
    explanation: 'La Barge Coloniale est consommée lors de la colonisation. Chaque colonie multiplie votre production totale.',
    hint: 'Vous aurez besoin de la Xéno-Cartographie et d\'un Réacteur à Impulsions niv. 3.',
    category: 'exploration',
    checkType: 'ship_count',
    checkTarget: 'colonyShip',
    checkValue: 1,
    validationSource: 'shipyard_complete',
    reward: { type: 'resources', fer: 15000, silice: 15000, xenogas: 10000 },
    navigateTo: '/(tabs)/shipyard?scrollTo=colonyShip',
  },
  {
    id: 'ch5_first_colony',
    chapterId: 'ch5',
    order: 24,
    title: 'Nouveau monde',
    description: 'Colonisez une planète vierge avec succès.',
    explanation: 'Trouvez une position vide dans la Galaxie et envoyez votre Barge. La position influence la température, les bonus et le nombre de cases. La colonie doit être créée avec succès.',
    hint: 'Envoyez votre Barge Coloniale vers une position vide dans la Galaxie avec la mission Coloniser.',
    category: 'exploration',
    checkType: 'server_event',
    checkTarget: 'colony_created',
    checkValue: 1,
    validationSource: 'colony_created',
    reward: { type: 'solar', solar: 150 },
    navigateTo: '/(tabs)/galaxy',
  },
  {
    id: 'ch5_fleet_5_scouts',
    chapterId: 'ch5',
    order: 25,
    title: 'Escadron de chasse',
    description: 'Assemblez une flotte de 5 Nova Scouts.',
    explanation: 'La force est dans le nombre. Un escadron complet vous permet de mener des raids efficaces et de protéger vos convois.',
    hint: 'La force est dans le nombre !',
    category: 'military',
    checkType: 'ship_count',
    checkTarget: 'novaScout',
    checkValue: 5,
    validationSource: 'shipyard_complete',
    reward: { type: 'solar', solar: 100 },
    navigateTo: '/(tabs)/shipyard?scrollTo=novaScout',
  },
  {
    id: 'ch5_ferro_mine_5',
    chapterId: 'ch5',
    order: 26,
    title: 'Empire minier',
    description: 'Améliorez la Ferro Mine au niveau 5 sur votre planète principale.',
    explanation: 'Une économie solide est le pilier de tout empire durable. Plus vos mines sont hautes, plus votre croissance est rapide. N\'oubliez pas l\'énergie !',
    hint: 'Une économie solide est la base de tout empire.',
    category: 'economy',
    checkType: 'building_level',
    checkTarget: 'ferMine',
    checkValue: 5,
    validationSource: 'building_complete',
    reward: { type: 'solar', solar: 75 },
    navigateTo: '/(tabs)/buildings?scrollTo=ferMine',
  },
];

export const TUTORIAL_CATEGORIES = {
  economy: { label: 'Économie', color: '#D4A847' },
  facilities: { label: 'Infrastructures', color: '#8B5CF6' },
  research: { label: 'Recherche', color: '#22D3EE' },
  military: { label: 'Militaire', color: '#EF4444' },
  exploration: { label: 'Exploration', color: '#10B981' },
} as const;

export function getStepByIndex(index: number): TutorialStep | null {
  return TUTORIAL_STEPS[index] ?? null;
}

export function getNextStep(currentStepId: string): TutorialStep | null {
  const idx = TUTORIAL_STEPS.findIndex(s => s.id === currentStepId);
  if (idx < 0 || idx >= TUTORIAL_STEPS.length - 1) return null;
  return TUTORIAL_STEPS[idx + 1];
}

export function getChapterForStep(stepId: string): TutorialChapter | null {
  const step = TUTORIAL_STEPS.find(s => s.id === stepId);
  if (!step) return null;
  return TUTORIAL_CHAPTERS.find(c => c.id === step.chapterId) ?? null;
}
